server:
  url: http://localhost:8080/api
  port: 8080

frontend:
  url: http://localhost:3000

jwt:
  secret: super_secret # Use a secure, long random string in production
  expirationMs: 86400000 # 24 hours

database:
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: postgres
